a = input("Digite algo: ")

print("O tipo primitivo deste valor é:", type(a))
print("Só tem espaços: ", a.isspace())
print("É un múmero: ", a.isnumeric())
print("É alfabetico: ", a.isalpha())
print("É alfanumerico: ", a.isalnum())
print("Esta em maiusculas : ", a.isupper())
print("Esta em minuscula : ", a.islower())
print("Esta capitalizada : ", a.istitle())